### PR TITLE
Added maintainers and contribution text to README

### PR DESCRIPTION
**Pull request by mjbrender**
I want to keep the README with these two sections.

### CODE REVIEW

**Comment by mjbrender** [comment]
Hey @haf & @danieldreier - please confirm that you're comfortable with being noted as maintainers and authors. **Thank you** for this incredible work.

**Comment by danieldreier** [comment]
+1

**Comment by danieldreier** [comment]
@mjbrender you should list yourself, too.

**Comment by mjbrender** [comment]
:blush: why thank you - I will!

**Pull request merged**
